name: Issue Workflow
on: issues

jobs:
 output-info:
    runs-on: ubuntu-latest
    steps:
        - name: Outout event details
          run : | 
             echo "${{github}}" 
             echo "====================================================="
             echo "${{github.event}}   ${{github.event_name}}   ${{github.event_path}}" 
             echo "====================================================="
             echo ${{env}}
             echo "====================================================="
             echo ${{vars}}
             echo "====================================================="
             echo ${{runner}}
             echo "====================================================="
             echo ${{job}}
             echo "====================================================="
             echo ${{matrix}}
             echo "====================================================="
             echo ${{needs}}
             echo "====================================================="
             echo ${{inputs}}
             echo "====================================================="


